no-src/gofs

- README-CN.md
- README.md
- cmd/gofs/flag.go
- cmd/gofs/main.go
- contract/file_server_info.go
- contract/params.go
- monitor/fsnotify_monitor.go
- monitor/monitor.go
- monitor/remote_client_monitor.go
- server/README.md
- server/fs/file_server.go
- server/handler/default_handler.go
- server/handler/file_api_handler.go
- server/option.go
- server/server.go
- server/template/index.html
- sync/disk_sync.go
- sync/remote_client_sync.go
- sync/remote_server_sync.go
- sync/remote_sync.go
- sync/sync.go
Rename `target` to `dest`.
Rename `src` to `source`.
> Rename the `src` flag and `target` flag

- internal/cbool/cbool.go
- monitor/remote_client_monitor.go
- tran/tcpclient.go
- tran/tcpserver.go
> Fix the problem of data race

- .github/workflows/codeql.yml
- cmd/flag.go
- conf/config.go
- conf/example/gofs-remote-client.json
- conf/example/gofs-remote-server.yaml
- driver/sftp/dir.go
- driver/sftp/sftp.go
- server/httpfs/file_server.go
- server/option.go
- sync/option.go
- sync/sftp_pull_client_sync.go
- sync/sftp_push_client_sync.go
Fixes #47
[What are SSH Host Keys?](https://www.ssh.com/academy/ssh/host-key)
> Fix use of insecure HostKeyCallback implementation

- README-CN.md
- README.md
See the issue [8671](https://github.com/badges/shields/issues/8671).
> Update the build badge

- internal/clist/clist_benchmark_test.go
- internal/clist/clist_test.go
go1.19.5 windows/amd64
```
goos: windows
goarch: amd64
pkg: github.com/no-src/gofs/internal/clist
cpu: Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
BenchmarkCList_PushBack
BenchmarkCList_PushBack-12       5567295               185.1 ns/op            55 B/op          1 allocs/op
BenchmarkCList_Front
BenchmarkCList_Front-12         60216374                18.32 ns/op            0 B/op          0 allocs/op
BenchmarkCList_Len
BenchmarkCList_Len-12           73139067                17.87 ns/op            0 B/op          0 allocs/op
BenchmarkCList
BenchmarkCList-12                6438019               185.5 ns/op            56 B/op          1 allocs/op
```
> Add some unit tests and benchmark tests for the clist package

- internal/toplist/toplist_benchmark_test.go
- internal/toplist/toplist_test.go
go1.19.5 windows/amd64
```
goos: windows
goarch: amd64
pkg: github.com/no-src/gofs/internal/toplist
cpu: Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
BenchmarkTopList_Add
BenchmarkTopList_Add-12                 24215566                57.12 ns/op               8 B/op          0 allocs/op
BenchmarkTopList_Get
BenchmarkTopList_Get-12                 59333388                21.21 ns/op               0 B/op          0 allocs/op
BenchmarkTopList_Top
BenchmarkTopList_Top-12                  2487188                521.0 ns/op             240 B/op          4 allocs/op
BenchmarkTopList_Len
BenchmarkTopList_Len-12                 58417548                18.94 ns/op               0 B/op          0 allocs/op
BenchmarkTopList_Cap
BenchmarkTopList_Cap-12                 70659726                20.61 ns/op …
```
> Add some unit tests and benchmark tests for the toplist package

- Dockerfile
- scripts/build-docker.sh
golang:latest => golang:alpine
alpine:3.15.4 => alpine:latest
> Update base images in the Dockerfile

- .github/workflows/go.yml
- auth/auth_test.go
- auth/user.go
- checksum/checksum.go
- checksum/checksum_test.go
- cmd/gofs.go
- server/handler/file_api_handler.go
- server/handler/push_handler.go
- server/httpfs/file_server.go
- server/option.go
- sync/disk_sync.go
- sync/driver_pull_client_sync.go
- sync/option.go
- sync/push_client_sync.go
- sync/remote_client_sync.go
- sync/remote_server_sync.go
- util/hashutil/compare.go
- util/hashutil/compare_test.go
- util/hashutil/factory.go
- util/hashutil/factory_test.go
- util/hashutil/hash.go
- util/hashutil/hash_benchmark_test.go
- util/hashutil/hash_test.go
> Remove the global variables in the hashutil package

- .github/workflows/go.yml
- go.mod
- go.sum
Fixes integration tests error from #131
> Enable integration tests and update dependency, github.com/no-src/fsctl v0.1.0 => v0.1.1

- server/httpfs/file_server.go
- server/server.go
- sync/option.go
- sync/remote_server_sync.go
> Remove the global variables in the server package

- cmd/gofs.go
- server/client/login.go
- sync/option.go
- sync/push_client_sync.go
- sync/remote_client_sync.go
- util/httputil/client.go
- util/httputil/http.go
- util/httputil/http_test.go
> Remove the global variables in the httputil package

- cmd/gofs.go
- daemon/daemon.go
> Remove the global variable in the daemon package

- cmd/gofs.go
- monitor/fsnotify_monitor.go
- monitor/option.go
- report/reporter.go
- report/reporter_test.go
- server/handler/report_handler.go
- server/httpfs/file_server.go
- server/middleware/api_stat.go
- server/option.go
- sync/option.go
- sync/remote_server_sync.go
- tran/conn.go
- tran/conn_test.go
- tran/tcpclient_test.go
- tran/tcpserver.go
- tran/tcpserver_test.go
> Remove the global variable GlobalReporter

- Dockerfile
- scripts/build-docker.sh
golang:alpine => golang:latest
> Revert base image in the Dockerfile

- fs/fs.go
- fs/fs_test.go
- integration/integration_test.go
- integration/testdata/test/test-gofs-remote-disk.yaml
- integration/testdata/test/test-gofs-remote-push.yaml
- monitor/remote_client_monitor.go
- server/handler/file_api_handler.go
- sync/remote_client_sync.go
> Fix some special characters may break the file path

- api/task/loader/file.go
- api/task/loader/loader_test.go
- driver/driver.go
- driver/minio/dir_file_info.go
- driver/minio/file_info.go
- driver/minio/minio.go
- driver/sftp/sftp.go
- encrypt/decrypt.go
- encrypt/decrypt_reader.go
- encrypt/decrypt_test.go
- encrypt/encrypt_test.go
- fs/fs.go
- server/handler/push_handler.go
- sync/disk_sync.go
- sync/driver_push_client_sync.go
- sync/remote_client_sync.go
Replace os.ModePerm with fs.ModePerm.
Replace os.FileInfo with fs.FileInfo.
Replace os.FileMode with fs.FileMode.
Replace minio.statDirEntry and sftp.statDirEntry with fs.FileInfoToDirEntry.
> Code refactoring with io/fs package

- Dockerfile
- scripts/build-release.sh
Get last git commit from `HEAD`.
> Code refactoring for scripts/build-release.sh

- .github/workflows/go.yml
- scripts/init-env.sh
https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
> Add init-env.sh script to fix the UDP buffer sizes

- api/api_test.go
- cmd/gofs.go
- core/path.go
- core/vfs.go
- driver/minio/minio.go
- integration/integration_minio_test.go
- integration/testdata/conf/run-gofs-minio-pull-client-partial.yaml
- integration/testdata/conf/run-gofs-minio-push-client-partial.yaml
- integration/testdata/test/test-gofs-minio-pull-partial.yaml
- integration/testdata/test/test-gofs-minio-push-partial.yaml
- monitor/driver_pull_client_monitor.go
- monitor/fsnotify_monitor.go
- server/handler/push_handler.go
- server/httpfs/file_server.go
- sync/minio_pull_client_sync.go
- sync/minio_push_client_sync.go
- sync/sftp_pull_client_sync.go
- sync/sftp_push_client_sync.go
For [Issues I8BSKJ](https://gitee.com/no-src/gofs/issues/I8BSKJ)
> Support specifying MinIO path in MinIO synchronization scenes

- api/apiclient/grpc_client.go
- api/apiclient/token.go
- integration/integration_remote_test.go
- integration/testdata/conf/run-gofs-remote-disk-client-with-insecure.yaml
- integration/testdata/conf/run-gofs-remote-disk-server-with-insecure.yaml
This is a temporary solution and will be removed in the future.
> Supports transport credentials with an insecure transport
